/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entry implements java.io.Serializable {

	private static final long serialVersionUID = 1526549362;

	private java.lang.Integer  entryId;
	private java.lang.Integer  userId;
	private java.lang.Integer  roomId;
	private java.lang.Integer  scheduleId;
	private java.lang.Byte     status;
	private java.sql.Date      startDate;
	private java.sql.Time      startTime;
	private java.sql.Date      endDate;
	private java.sql.Time      endTime;
	private java.lang.String   description;
	private java.lang.String   infoUser;
	private java.lang.String   infoText;
	private java.sql.Timestamp infoTime;
	private java.sql.Timestamp createTime;

	public Entry() {}

	public Entry(
		java.lang.Integer  entryId,
		java.lang.Integer  userId,
		java.lang.Integer  roomId,
		java.lang.Integer  scheduleId,
		java.lang.Byte     status,
		java.sql.Date      startDate,
		java.sql.Time      startTime,
		java.sql.Date      endDate,
		java.sql.Time      endTime,
		java.lang.String   description,
		java.lang.String   infoUser,
		java.lang.String   infoText,
		java.sql.Timestamp infoTime,
		java.sql.Timestamp createTime
	) {
		this.entryId = entryId;
		this.userId = userId;
		this.roomId = roomId;
		this.scheduleId = scheduleId;
		this.status = status;
		this.startDate = startDate;
		this.startTime = startTime;
		this.endDate = endDate;
		this.endTime = endTime;
		this.description = description;
		this.infoUser = infoUser;
		this.infoText = infoText;
		this.infoTime = infoTime;
		this.createTime = createTime;
	}

	public java.lang.Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(java.lang.Integer entryId) {
		this.entryId = entryId;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}

	public java.lang.Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(java.lang.Integer roomId) {
		this.roomId = roomId;
	}

	public java.lang.Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(java.lang.Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public java.lang.Byte getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Byte status) {
		this.status = status;
	}

	public java.sql.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.sql.Date startDate) {
		this.startDate = startDate;
	}

	public java.sql.Time getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.sql.Time startTime) {
		this.startTime = startTime;
	}

	public java.sql.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.sql.Date endDate) {
		this.endDate = endDate;
	}

	public java.sql.Time getEndTime() {
		return this.endTime;
	}

	public void setEndTime(java.sql.Time endTime) {
		this.endTime = endTime;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getInfoUser() {
		return this.infoUser;
	}

	public void setInfoUser(java.lang.String infoUser) {
		this.infoUser = infoUser;
	}

	public java.lang.String getInfoText() {
		return this.infoText;
	}

	public void setInfoText(java.lang.String infoText) {
		this.infoText = infoText;
	}

	public java.sql.Timestamp getInfoTime() {
		return this.infoTime;
	}

	public void setInfoTime(java.sql.Timestamp infoTime) {
		this.infoTime = infoTime;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}
}
