/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = 1611376650;

	private java.lang.Integer roleId;
	private java.lang.String  name;

	public Role() {}

	public Role(
		java.lang.Integer roleId,
		java.lang.String  name
	) {
		this.roleId = roleId;
		this.name = name;
	}

	public java.lang.Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(java.lang.Integer roleId) {
		this.roleId = roleId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}
}
