/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.pojos;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomEntry implements java.io.Serializable {

	private static final long serialVersionUID = 1468832681;

	private java.lang.String  roomName;
	private java.lang.String  fullName;
	private java.sql.Time     startTime;
	private java.sql.Time     endTime;
	private java.lang.String  name;
	private java.lang.Integer entryId;
	private java.lang.Integer entryRoomId;
	private java.lang.Integer entryUserId;
	private java.lang.Integer entryScheduleId;
	private java.lang.Byte    status;
	private java.lang.Integer userId;
	private java.lang.Integer scheduleId;
	private java.lang.Integer scheduleScheduleTypeId;
	private java.lang.Integer scheduleTypeId;
	private java.lang.Integer roomId;

	public RoomEntry() {}

	public RoomEntry(
		java.lang.String  roomName,
		java.lang.String  fullName,
		java.sql.Time     startTime,
		java.sql.Time     endTime,
		java.lang.String  name,
		java.lang.Integer entryId,
		java.lang.Integer entryRoomId,
		java.lang.Integer entryUserId,
		java.lang.Integer entryScheduleId,
		java.lang.Byte    status,
		java.lang.Integer userId,
		java.lang.Integer scheduleId,
		java.lang.Integer scheduleScheduleTypeId,
		java.lang.Integer scheduleTypeId,
		java.lang.Integer roomId
	) {
		this.roomName = roomName;
		this.fullName = fullName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.name = name;
		this.entryId = entryId;
		this.entryRoomId = entryRoomId;
		this.entryUserId = entryUserId;
		this.entryScheduleId = entryScheduleId;
		this.status = status;
		this.userId = userId;
		this.scheduleId = scheduleId;
		this.scheduleScheduleTypeId = scheduleScheduleTypeId;
		this.scheduleTypeId = scheduleTypeId;
		this.roomId = roomId;
	}

	public java.lang.String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(java.lang.String roomName) {
		this.roomName = roomName;
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.sql.Time getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.sql.Time startTime) {
		this.startTime = startTime;
	}

	public java.sql.Time getEndTime() {
		return this.endTime;
	}

	public void setEndTime(java.sql.Time endTime) {
		this.endTime = endTime;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(java.lang.Integer entryId) {
		this.entryId = entryId;
	}

	public java.lang.Integer getEntryRoomId() {
		return this.entryRoomId;
	}

	public void setEntryRoomId(java.lang.Integer entryRoomId) {
		this.entryRoomId = entryRoomId;
	}

	public java.lang.Integer getEntryUserId() {
		return this.entryUserId;
	}

	public void setEntryUserId(java.lang.Integer entryUserId) {
		this.entryUserId = entryUserId;
	}

	public java.lang.Integer getEntryScheduleId() {
		return this.entryScheduleId;
	}

	public void setEntryScheduleId(java.lang.Integer entryScheduleId) {
		this.entryScheduleId = entryScheduleId;
	}

	public java.lang.Byte getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Byte status) {
		this.status = status;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}

	public java.lang.Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(java.lang.Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public java.lang.Integer getScheduleScheduleTypeId() {
		return this.scheduleScheduleTypeId;
	}

	public void setScheduleScheduleTypeId(java.lang.Integer scheduleScheduleTypeId) {
		this.scheduleScheduleTypeId = scheduleScheduleTypeId;
	}

	public java.lang.Integer getScheduleTypeId() {
		return this.scheduleTypeId;
	}

	public void setScheduleTypeId(java.lang.Integer scheduleTypeId) {
		this.scheduleTypeId = scheduleTypeId;
	}

	public java.lang.Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(java.lang.Integer roomId) {
		this.roomId = roomId;
	}
}
