/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedule implements java.io.Serializable {

	private static final long serialVersionUID = 1450565041;

	private java.lang.Integer    scheduleId;
	private java.lang.Integer    scheduleTypeId;
	private org.jooq.types.UByte weakDay;
	private org.jooq.types.UByte monthDay;
	private org.jooq.types.UByte monthWeak;
	private org.jooq.types.UByte yearDay;
	private java.sql.Timestamp   createTime;

	public Schedule() {}

	public Schedule(
		java.lang.Integer    scheduleId,
		java.lang.Integer    scheduleTypeId,
		org.jooq.types.UByte weakDay,
		org.jooq.types.UByte monthDay,
		org.jooq.types.UByte monthWeak,
		org.jooq.types.UByte yearDay,
		java.sql.Timestamp   createTime
	) {
		this.scheduleId = scheduleId;
		this.scheduleTypeId = scheduleTypeId;
		this.weakDay = weakDay;
		this.monthDay = monthDay;
		this.monthWeak = monthWeak;
		this.yearDay = yearDay;
		this.createTime = createTime;
	}

	public java.lang.Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(java.lang.Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public java.lang.Integer getScheduleTypeId() {
		return this.scheduleTypeId;
	}

	public void setScheduleTypeId(java.lang.Integer scheduleTypeId) {
		this.scheduleTypeId = scheduleTypeId;
	}

	public org.jooq.types.UByte getWeakDay() {
		return this.weakDay;
	}

	public void setWeakDay(org.jooq.types.UByte weakDay) {
		this.weakDay = weakDay;
	}

	public org.jooq.types.UByte getMonthDay() {
		return this.monthDay;
	}

	public void setMonthDay(org.jooq.types.UByte monthDay) {
		this.monthDay = monthDay;
	}

	public org.jooq.types.UByte getMonthWeak() {
		return this.monthWeak;
	}

	public void setMonthWeak(org.jooq.types.UByte monthWeak) {
		this.monthWeak = monthWeak;
	}

	public org.jooq.types.UByte getYearDay() {
		return this.yearDay;
	}

	public void setYearDay(org.jooq.types.UByte yearDay) {
		this.yearDay = yearDay;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}
}
