/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntryDao extends org.jooq.impl.DAOImpl<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.pojos.Entry, java.lang.Integer> {

	/**
	 * Create a new EntryDao without any configuration
	 */
	public EntryDao() {
		super(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.pojos.Entry.class);
	}

	/**
	 * Create a new EntryDao with an attached configuration
	 */
	public EntryDao(org.jooq.Configuration configuration) {
		super(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.pojos.Entry.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.inf.uth.eydokia.jooq.tables.pojos.Entry object) {
		return object.getEntryId();
	}

	/**
	 * Fetch records that have <code>entry_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByEntryId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ENTRY_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>entry_id = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.Entry fetchOneByEntryId(java.lang.Integer value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ENTRY_ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByUserId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>room_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByRoomId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ROOM_ID, values);
	}

	/**
	 * Fetch records that have <code>schedule_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByScheduleId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.SCHEDULE_ID, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByStatus(java.lang.Byte... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.STATUS, values);
	}

	/**
	 * Fetch records that have <code>start_date IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByStartDate(java.sql.Date... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.START_DATE, values);
	}

	/**
	 * Fetch records that have <code>start_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByStartTime(java.sql.Time... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.START_TIME, values);
	}

	/**
	 * Fetch records that have <code>end_date IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByEndDate(java.sql.Date... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.END_DATE, values);
	}

	/**
	 * Fetch records that have <code>end_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByEndTime(java.sql.Time... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.END_TIME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByDescription(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>info_user IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByInfoUser(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_USER, values);
	}

	/**
	 * Fetch records that have <code>info_text IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByInfoText(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_TEXT, values);
	}

	/**
	 * Fetch records that have <code>info_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByInfoTime(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_TIME, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Entry> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.CREATE_TIME, values);
	}
}
