/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleDao extends org.jooq.impl.DAOImpl<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.inf.uth.eydokia.jooq.tables.pojos.Schedule, java.lang.Integer> {

	/**
	 * Create a new ScheduleDao without any configuration
	 */
	public ScheduleDao() {
		super(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE, org.inf.uth.eydokia.jooq.tables.pojos.Schedule.class);
	}

	/**
	 * Create a new ScheduleDao with an attached configuration
	 */
	public ScheduleDao(org.jooq.Configuration configuration) {
		super(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE, org.inf.uth.eydokia.jooq.tables.pojos.Schedule.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.inf.uth.eydokia.jooq.tables.pojos.Schedule object) {
		return object.getScheduleId();
	}

	/**
	 * Fetch records that have <code>schedule_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByScheduleId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>schedule_id = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.Schedule fetchOneByScheduleId(java.lang.Integer value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_ID, value);
	}

	/**
	 * Fetch records that have <code>schedule_type_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByScheduleTypeId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_TYPE_ID, values);
	}

	/**
	 * Fetch records that have <code>weak_day IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByWeakDay(org.jooq.types.UByte... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.WEAK_DAY, values);
	}

	/**
	 * Fetch records that have <code>month_day IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByMonthDay(org.jooq.types.UByte... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.MONTH_DAY, values);
	}

	/**
	 * Fetch records that have <code>month_weak IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByMonthWeak(org.jooq.types.UByte... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.MONTH_WEAK, values);
	}

	/**
	 * Fetch records that have <code>year_day IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByYearDay(org.jooq.types.UByte... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.YEAR_DAY, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Schedule> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.CREATE_TIME, values);
	}
}
