/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = 1307400418;

	/**
	 * The reference instance of <code>eydokia.user</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.User USER = new org.inf.uth.eydokia.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.UserRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>eydokia.user.user_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.user.role_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.user.email</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>eydokia.user.full_name</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>eydokia.user.phone</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>eydokia.user.username</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

	/**
	 * The column <code>eydokia.user.password</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>eydokia.user.extra_info</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.lang.String> EXTRA_INFO = createField("extra_info", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>eydokia.user.create_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.UserRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>eydokia.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>eydokia.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> getPrimaryKey() {
		return org.inf.uth.eydokia.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord>>asList(org.inf.uth.eydokia.jooq.Keys.KEY_USER_PRIMARY, org.inf.uth.eydokia.jooq.Keys.KEY_USER_EMAIL_UNIQUE, org.inf.uth.eydokia.jooq.Keys.KEY_USER_USERNAME_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord, ?>>asList(org.inf.uth.eydokia.jooq.Keys.ROLE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.User as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.User rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.User(name, null);
	}
}
