/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleRecord extends org.jooq.impl.UpdatableRecordImpl<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp> {

	private static final long serialVersionUID = -828954053;

	/**
	 * Setter for <code>eydokia.schedule.schedule_id</code>.
	 */
	public void setScheduleId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.schedule_id</code>.
	 */
	public java.lang.Integer getScheduleId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>eydokia.schedule.schedule_type_id</code>.
	 */
	public void setScheduleTypeId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.schedule_type_id</code>.
	 */
	public java.lang.Integer getScheduleTypeId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>eydokia.schedule.weak_day</code>.
	 */
	public void setWeakDay(org.jooq.types.UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.weak_day</code>.
	 */
	public org.jooq.types.UByte getWeakDay() {
		return (org.jooq.types.UByte) getValue(2);
	}

	/**
	 * Setter for <code>eydokia.schedule.month_day</code>.
	 */
	public void setMonthDay(org.jooq.types.UByte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.month_day</code>.
	 */
	public org.jooq.types.UByte getMonthDay() {
		return (org.jooq.types.UByte) getValue(3);
	}

	/**
	 * Setter for <code>eydokia.schedule.month_weak</code>.
	 */
	public void setMonthWeak(org.jooq.types.UByte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.month_weak</code>.
	 */
	public org.jooq.types.UByte getMonthWeak() {
		return (org.jooq.types.UByte) getValue(4);
	}

	/**
	 * Setter for <code>eydokia.schedule.year_day</code>.
	 */
	public void setYearDay(org.jooq.types.UByte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.year_day</code>.
	 */
	public org.jooq.types.UByte getYearDay() {
		return (org.jooq.types.UByte) getValue(5);
	}

	/**
	 * Setter for <code>eydokia.schedule.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>eydokia.schedule.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, org.jooq.types.UByte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field3() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.WEAK_DAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field4() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.MONTH_DAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field5() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.MONTH_WEAK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field6() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.YEAR_DAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getScheduleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getScheduleTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value3() {
		return getWeakDay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value4() {
		return getMonthDay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value5() {
		return getMonthWeak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value6() {
		return getYearDay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value1(java.lang.Integer value) {
		setScheduleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value2(java.lang.Integer value) {
		setScheduleTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value3(org.jooq.types.UByte value) {
		setWeakDay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value4(org.jooq.types.UByte value) {
		setMonthDay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value5(org.jooq.types.UByte value) {
		setMonthWeak(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value6(org.jooq.types.UByte value) {
		setYearDay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord value7(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScheduleRecord values(java.lang.Integer value1, java.lang.Integer value2, org.jooq.types.UByte value3, org.jooq.types.UByte value4, org.jooq.types.UByte value5, org.jooq.types.UByte value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScheduleRecord
	 */
	public ScheduleRecord() {
		super(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE);
	}

	/**
	 * Create a detached, initialised ScheduleRecord
	 */
	public ScheduleRecord(java.lang.Integer scheduleId, java.lang.Integer scheduleTypeId, org.jooq.types.UByte weakDay, org.jooq.types.UByte monthDay, org.jooq.types.UByte monthWeak, org.jooq.types.UByte yearDay, java.sql.Timestamp createTime) {
		super(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE);

		setValue(0, scheduleId);
		setValue(1, scheduleTypeId);
		setValue(2, weakDay);
		setValue(3, monthDay);
		setValue(4, monthWeak);
		setValue(5, yearDay);
		setValue(6, createTime);
	}
}
