/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Eydokia extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 794948220;

	/**
	 * The reference instance of <code>eydokia</code>
	 */
	public static final Eydokia EYDOKIA = new Eydokia();

	/**
	 * No further instances allowed
	 */
	private Eydokia() {
		super("eydokia");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.inf.uth.eydokia.jooq.tables.Entry.ENTRY,
			org.inf.uth.eydokia.jooq.tables.Role.ROLE,
			org.inf.uth.eydokia.jooq.tables.Room.ROOM,
			org.inf.uth.eydokia.jooq.tables.RoomEntry.ROOM_ENTRY,
			org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE,
			org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE,
			org.inf.uth.eydokia.jooq.tables.User.USER);
	}
}
