/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq;

/**
 * Convenience access to all tables in eydokia
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table eydokia.entry
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Entry ENTRY = org.inf.uth.eydokia.jooq.tables.Entry.ENTRY;

	/**
	 * The table eydokia.role
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Role ROLE = org.inf.uth.eydokia.jooq.tables.Role.ROLE;

	/**
	 * The table eydokia.room
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Room ROOM = org.inf.uth.eydokia.jooq.tables.Room.ROOM;

	/**
	 * VIEW
	 */
	public static final org.inf.uth.eydokia.jooq.tables.RoomEntry ROOM_ENTRY = org.inf.uth.eydokia.jooq.tables.RoomEntry.ROOM_ENTRY;

	/**
	 * The table eydokia.schedule
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Schedule SCHEDULE = org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE;

	/**
	 * The table eydokia.schedule_type
	 */
	public static final org.inf.uth.eydokia.jooq.tables.ScheduleType SCHEDULE_TYPE = org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE;

	/**
	 * The table eydokia.user
	 */
	public static final org.inf.uth.eydokia.jooq.tables.User USER = org.inf.uth.eydokia.jooq.tables.User.USER;
}
