/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entry extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> {

	private static final long serialVersionUID = -1520700450;

	/**
	 * The reference instance of <code>eydokia.entry</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Entry ENTRY = new org.inf.uth.eydokia.jooq.tables.Entry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.EntryRecord.class;
	}

	/**
	 * The column <code>eydokia.entry.entry_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> ENTRY_ID = createField("entry_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.entry.user_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.entry.room_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.entry.schedule_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> SCHEDULE_ID = createField("schedule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.entry.status</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.entry.start_date</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Date> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>eydokia.entry.start_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Time> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>eydokia.entry.end_date</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Date> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>eydokia.entry.end_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Time> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>eydokia.entry.description</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>eydokia.entry.info_user</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.String> INFO_USER = createField("info_user", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>eydokia.entry.info_text</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.String> INFO_TEXT = createField("info_text", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>eydokia.entry.info_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Timestamp> INFO_TIME = createField("info_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>eydokia.entry.create_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>eydokia.entry</code> table reference
	 */
	public Entry() {
		this("entry", null);
	}

	/**
	 * Create an aliased <code>eydokia.entry</code> table reference
	 */
	public Entry(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY);
	}

	private Entry(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Entry(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> getIdentity() {
		return org.inf.uth.eydokia.jooq.Keys.IDENTITY_ENTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> getPrimaryKey() {
		return org.inf.uth.eydokia.jooq.Keys.KEY_ENTRY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord>>asList(org.inf.uth.eydokia.jooq.Keys.KEY_ENTRY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, ?>>asList(org.inf.uth.eydokia.jooq.Keys.USER_ID, org.inf.uth.eydokia.jooq.Keys.ROOM_ID, org.inf.uth.eydokia.jooq.Keys.SCHEDULE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.Entry as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.Entry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.Entry rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.Entry(name, null);
	}
}
