/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> {

	private static final long serialVersionUID = 1896574040;

	/**
	 * The reference instance of <code>eydokia.events</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Events EVENTS = new org.inf.uth.eydokia.jooq.tables.Events();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.EventsRecord.class;
	}

	/**
	 * The column <code>eydokia.events.id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.events.start_date</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, java.sql.Timestamp> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>eydokia.events.end_date</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, java.sql.Timestamp> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>eydokia.events.text</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>eydokia.events</code> table reference
	 */
	public Events() {
		this("events", null);
	}

	/**
	 * Create an aliased <code>eydokia.events</code> table reference
	 */
	public Events(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.Events.EVENTS);
	}

	private Events(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Events(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, java.lang.Integer> getIdentity() {
		return org.inf.uth.eydokia.jooq.Keys.IDENTITY_EVENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> getPrimaryKey() {
		return org.inf.uth.eydokia.jooq.Keys.KEY_EVENTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EventsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EventsRecord>>asList(org.inf.uth.eydokia.jooq.Keys.KEY_EVENTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.Events as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.Events(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.Events rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.Events(name, null);
	}
}
