/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedule extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> {

	private static final long serialVersionUID = -649804105;

	/**
	 * The reference instance of <code>eydokia.schedule</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.Schedule SCHEDULE = new org.inf.uth.eydokia.jooq.tables.Schedule();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord.class;
	}

	/**
	 * The column <code>eydokia.schedule.schedule_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.lang.Integer> SCHEDULE_ID = createField("schedule_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.schedule.schedule_type_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.lang.Integer> SCHEDULE_TYPE_ID = createField("schedule_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.schedule.weak_day</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.jooq.types.UByte> WEAK_DAY = createField("weak_day", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.schedule.month_day</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.jooq.types.UByte> MONTH_DAY = createField("month_day", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.schedule.month_weak</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.jooq.types.UByte> MONTH_WEAK = createField("month_weak", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.schedule.year_day</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.jooq.types.UByte> YEAR_DAY = createField("year_day", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.schedule.create_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>eydokia.schedule</code> table reference
	 */
	public Schedule() {
		this("schedule", null);
	}

	/**
	 * Create an aliased <code>eydokia.schedule</code> table reference
	 */
	public Schedule(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE);
	}

	private Schedule(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> aliased) {
		this(alias, aliased, null);
	}

	private Schedule(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.lang.Integer> getIdentity() {
		return org.inf.uth.eydokia.jooq.Keys.IDENTITY_SCHEDULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> getPrimaryKey() {
		return org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord>>asList(org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, ?>>asList(org.inf.uth.eydokia.jooq.Keys.SCHEDULE_TYPE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.Schedule as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.Schedule(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.Schedule rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.Schedule(name, null);
	}
}
