/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * VIEW
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomEntry extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord> {

	private static final long serialVersionUID = -1617139796;

	/**
	 * The reference instance of <code>eydokia.room_entry</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.RoomEntry ROOM_ENTRY = new org.inf.uth.eydokia.jooq.tables.RoomEntry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord.class;
	}

	/**
	 * The column <code>eydokia.room_entry.room_name</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.String> ROOM_NAME = createField("room_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>eydokia.room_entry.full_name</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>eydokia.room_entry.start_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.sql.Time> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>eydokia.room_entry.end_time</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.sql.Time> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>eydokia.room_entry.name</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>eydokia.room_entry.entry_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> ENTRY_ID = createField("entry_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>eydokia.room_entry.entry_room_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> ENTRY_ROOM_ID = createField("entry_room_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.room_entry.entry_user_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> ENTRY_USER_ID = createField("entry_user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.room_entry.entry_schedule_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> ENTRY_SCHEDULE_ID = createField("entry_schedule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.room_entry.status</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>eydokia.room_entry.user_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.room_entry.schedule_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> SCHEDULE_ID = createField("schedule_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>eydokia.room_entry.schedule_schedule_type_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> SCHEDULE_SCHEDULE_TYPE_ID = createField("schedule_schedule_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>eydokia.room_entry.schedule_type_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> SCHEDULE_TYPE_ID = createField("schedule_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>eydokia.room_entry.room_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord, java.lang.Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>eydokia.room_entry</code> table reference
	 */
	public RoomEntry() {
		this("room_entry", null);
	}

	/**
	 * Create an aliased <code>eydokia.room_entry</code> table reference
	 */
	public RoomEntry(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.RoomEntry.ROOM_ENTRY);
	}

	private RoomEntry(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord> aliased) {
		this(alias, aliased, null);
	}

	private RoomEntry(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.RoomEntryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.RoomEntry as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.RoomEntry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.RoomEntry rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.RoomEntry(name, null);
	}
}
