/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleType extends org.jooq.impl.TableImpl<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> {

	private static final long serialVersionUID = -591150765;

	/**
	 * The reference instance of <code>eydokia.schedule_type</code>
	 */
	public static final org.inf.uth.eydokia.jooq.tables.ScheduleType SCHEDULE_TYPE = new org.inf.uth.eydokia.jooq.tables.ScheduleType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> getRecordType() {
		return org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord.class;
	}

	/**
	 * The column <code>eydokia.schedule_type.schedule_type_id</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, java.lang.Integer> SCHEDULE_TYPE_ID = createField("schedule_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>eydokia.schedule_type.name</code>.
	 */
	public final org.jooq.TableField<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * Create a <code>eydokia.schedule_type</code> table reference
	 */
	public ScheduleType() {
		this("schedule_type", null);
	}

	/**
	 * Create an aliased <code>eydokia.schedule_type</code> table reference
	 */
	public ScheduleType(java.lang.String alias) {
		this(alias, org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE);
	}

	private ScheduleType(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScheduleType(java.lang.String alias, org.jooq.Table<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.inf.uth.eydokia.jooq.Eydokia.EYDOKIA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, java.lang.Integer> getIdentity() {
		return org.inf.uth.eydokia.jooq.Keys.IDENTITY_SCHEDULE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> getPrimaryKey() {
		return org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord>>asList(org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.inf.uth.eydokia.jooq.tables.ScheduleType as(java.lang.String alias) {
		return new org.inf.uth.eydokia.jooq.tables.ScheduleType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.inf.uth.eydokia.jooq.tables.ScheduleType rename(java.lang.String name) {
		return new org.inf.uth.eydokia.jooq.tables.ScheduleType(name, null);
	}
}
