/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>eydokia</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> IDENTITY_ENTRY = Identities0.IDENTITY_ENTRY;
	public static final org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.RoleRecord, java.lang.Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
	public static final org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.RoomRecord, java.lang.Integer> IDENTITY_ROOM = Identities0.IDENTITY_ROOM;
	public static final org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.lang.Integer> IDENTITY_SCHEDULE = Identities0.IDENTITY_SCHEDULE;
	public static final org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, java.lang.Integer> IDENTITY_SCHEDULE_TYPE = Identities0.IDENTITY_SCHEDULE_TYPE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> KEY_ENTRY_PRIMARY = UniqueKeys0.KEY_ENTRY_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.RoomRecord> KEY_ROOM_PRIMARY = UniqueKeys0.KEY_ROOM_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> KEY_SCHEDULE_PRIMARY = UniqueKeys0.KEY_SCHEDULE_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> KEY_SCHEDULE_TYPE_PRIMARY = UniqueKeys0.KEY_SCHEDULE_TYPE_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_EMAIL_UNIQUE = UniqueKeys0.KEY_USER_EMAIL_UNIQUE;
	public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_USERNAME_UNIQUE = UniqueKeys0.KEY_USER_USERNAME_UNIQUE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.UserRecord> USER_ID = ForeignKeys0.USER_ID;
	public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.RoomRecord> ROOM_ID = ForeignKeys0.ROOM_ID;
	public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> SCHEDULE_ID = ForeignKeys0.SCHEDULE_ID;
	public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> SCHEDULE_TYPE_ID = ForeignKeys0.SCHEDULE_TYPE_ID;
	public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord, org.inf.uth.eydokia.jooq.tables.records.RoleRecord> ROLE_ID = ForeignKeys0.ROLE_ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, java.lang.Integer> IDENTITY_ENTRY = createIdentity(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ENTRY_ID);
		public static org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.RoleRecord, java.lang.Integer> IDENTITY_ROLE = createIdentity(org.inf.uth.eydokia.jooq.tables.Role.ROLE, org.inf.uth.eydokia.jooq.tables.Role.ROLE.ROLE_ID);
		public static org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.RoomRecord, java.lang.Integer> IDENTITY_ROOM = createIdentity(org.inf.uth.eydokia.jooq.tables.Room.ROOM, org.inf.uth.eydokia.jooq.tables.Room.ROOM.ROOM_ID);
		public static org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, java.lang.Integer> IDENTITY_SCHEDULE = createIdentity(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE, org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_ID);
		public static org.jooq.Identity<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, java.lang.Integer> IDENTITY_SCHEDULE_TYPE = createIdentity(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE, org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE.SCHEDULE_TYPE_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> KEY_ENTRY_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ENTRY_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.Role.ROLE, org.inf.uth.eydokia.jooq.tables.Role.ROLE.ROLE_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.RoomRecord> KEY_ROOM_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.Room.ROOM, org.inf.uth.eydokia.jooq.tables.Room.ROOM.ROOM_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> KEY_SCHEDULE_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE, org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> KEY_SCHEDULE_TYPE_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE, org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE.SCHEDULE_TYPE_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.User.USER.USER_ID);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_EMAIL_UNIQUE = createUniqueKey(org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.User.USER.EMAIL);
		public static final org.jooq.UniqueKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord> KEY_USER_USERNAME_UNIQUE = createUniqueKey(org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.User.USER.USERNAME);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.UserRecord> USER_ID = createForeignKey(org.inf.uth.eydokia.jooq.Keys.KEY_USER_PRIMARY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.USER_ID);
		public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.RoomRecord> ROOM_ID = createForeignKey(org.inf.uth.eydokia.jooq.Keys.KEY_ROOM_PRIMARY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ROOM_ID);
		public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.EntryRecord, org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord> SCHEDULE_ID = createForeignKey(org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_PRIMARY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY, org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.SCHEDULE_ID);
		public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.ScheduleRecord, org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord> SCHEDULE_TYPE_ID = createForeignKey(org.inf.uth.eydokia.jooq.Keys.KEY_SCHEDULE_TYPE_PRIMARY, org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE, org.inf.uth.eydokia.jooq.tables.Schedule.SCHEDULE.SCHEDULE_TYPE_ID);
		public static final org.jooq.ForeignKey<org.inf.uth.eydokia.jooq.tables.records.UserRecord, org.inf.uth.eydokia.jooq.tables.records.RoleRecord> ROLE_ID = createForeignKey(org.inf.uth.eydokia.jooq.Keys.KEY_ROLE_PRIMARY, org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.User.USER.ROLE_ID);
	}
}
