/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsDao extends org.jooq.impl.DAOImpl<org.inf.uth.eydokia.jooq.tables.records.EventsRecord, org.inf.uth.eydokia.jooq.tables.pojos.Events, java.lang.Integer> {

	/**
	 * Create a new EventsDao without any configuration
	 */
	public EventsDao() {
		super(org.inf.uth.eydokia.jooq.tables.Events.EVENTS, org.inf.uth.eydokia.jooq.tables.pojos.Events.class);
	}

	/**
	 * Create a new EventsDao with an attached configuration
	 */
	public EventsDao(org.jooq.Configuration configuration) {
		super(org.inf.uth.eydokia.jooq.tables.Events.EVENTS, org.inf.uth.eydokia.jooq.tables.pojos.Events.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.inf.uth.eydokia.jooq.tables.pojos.Events object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Events> fetchById(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Events.EVENTS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.Events fetchOneById(java.lang.Integer value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.Events.EVENTS.ID, value);
	}

	/**
	 * Fetch records that have <code>start_date IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Events> fetchByStartDate(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Events.EVENTS.START_DATE, values);
	}

	/**
	 * Fetch records that have <code>end_date IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Events> fetchByEndDate(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Events.EVENTS.END_DATE, values);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.Events> fetchByText(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.Events.EVENTS.TEXT, values);
	}
}
