/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleTypeDao extends org.jooq.impl.DAOImpl<org.inf.uth.eydokia.jooq.tables.records.ScheduleTypeRecord, org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType, java.lang.Integer> {

	/**
	 * Create a new ScheduleTypeDao without any configuration
	 */
	public ScheduleTypeDao() {
		super(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE, org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType.class);
	}

	/**
	 * Create a new ScheduleTypeDao with an attached configuration
	 */
	public ScheduleTypeDao(org.jooq.Configuration configuration) {
		super(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE, org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType object) {
		return object.getScheduleTypeId();
	}

	/**
	 * Fetch records that have <code>schedule_type_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType> fetchByScheduleTypeId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE.SCHEDULE_TYPE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>schedule_type_id = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType fetchOneByScheduleTypeId(java.lang.Integer value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE.SCHEDULE_TYPE_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.ScheduleType> fetchByName(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.ScheduleType.SCHEDULE_TYPE.NAME, values);
	}
}
