/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends org.jooq.impl.DAOImpl<org.inf.uth.eydokia.jooq.tables.records.UserRecord, org.inf.uth.eydokia.jooq.tables.pojos.User, java.lang.Integer> {

	/**
	 * Create a new UserDao without any configuration
	 */
	public UserDao() {
		super(org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.pojos.User.class);
	}

	/**
	 * Create a new UserDao with an attached configuration
	 */
	public UserDao(org.jooq.Configuration configuration) {
		super(org.inf.uth.eydokia.jooq.tables.User.USER, org.inf.uth.eydokia.jooq.tables.pojos.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(org.inf.uth.eydokia.jooq.tables.pojos.User object) {
		return object.getUserId();
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByUserId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.User fetchOneByUserId(java.lang.Integer value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.User.USER.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>role_id IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByRoleId(java.lang.Integer... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.ROLE_ID, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByEmail(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.EMAIL, values);
	}

	/**
	 * Fetch a unique record that has <code>email = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.User fetchOneByEmail(java.lang.String value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.User.USER.EMAIL, value);
	}

	/**
	 * Fetch records that have <code>full_name IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByFullName(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.FULL_NAME, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByPhone(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.PHONE, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByUsername(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.USERNAME, values);
	}

	/**
	 * Fetch a unique record that has <code>username = value</code>
	 */
	public org.inf.uth.eydokia.jooq.tables.pojos.User fetchOneByUsername(java.lang.String value) {
		return fetchOne(org.inf.uth.eydokia.jooq.tables.User.USER.USERNAME, value);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByPassword(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>extra_info IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByExtraInfo(java.lang.String... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.EXTRA_INFO, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<org.inf.uth.eydokia.jooq.tables.pojos.User> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(org.inf.uth.eydokia.jooq.tables.User.USER.CREATE_TIME, values);
	}
}
