/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntryRecord extends org.jooq.impl.UpdatableRecordImpl<org.inf.uth.eydokia.jooq.tables.records.EntryRecord> implements org.jooq.Record14<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Date, java.sql.Time, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -986851611;

	/**
	 * Setter for <code>eydokia.entry.entry_id</code>.
	 */
	public void setEntryId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eydokia.entry.entry_id</code>.
	 */
	public java.lang.Integer getEntryId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>eydokia.entry.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eydokia.entry.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>eydokia.entry.room_id</code>.
	 */
	public void setRoomId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eydokia.entry.room_id</code>.
	 */
	public java.lang.Integer getRoomId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>eydokia.entry.schedule_id</code>.
	 */
	public void setScheduleId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eydokia.entry.schedule_id</code>.
	 */
	public java.lang.Integer getScheduleId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>eydokia.entry.status</code>.
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eydokia.entry.status</code>.
	 */
	public java.lang.Byte getStatus() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>eydokia.entry.start_date</code>.
	 */
	public void setStartDate(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eydokia.entry.start_date</code>.
	 */
	public java.sql.Date getStartDate() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>eydokia.entry.start_time</code>.
	 */
	public void setStartTime(java.sql.Time value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>eydokia.entry.start_time</code>.
	 */
	public java.sql.Time getStartTime() {
		return (java.sql.Time) getValue(6);
	}

	/**
	 * Setter for <code>eydokia.entry.end_date</code>.
	 */
	public void setEndDate(java.sql.Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>eydokia.entry.end_date</code>.
	 */
	public java.sql.Date getEndDate() {
		return (java.sql.Date) getValue(7);
	}

	/**
	 * Setter for <code>eydokia.entry.end_time</code>.
	 */
	public void setEndTime(java.sql.Time value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>eydokia.entry.end_time</code>.
	 */
	public java.sql.Time getEndTime() {
		return (java.sql.Time) getValue(8);
	}

	/**
	 * Setter for <code>eydokia.entry.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>eydokia.entry.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>eydokia.entry.info_user</code>.
	 */
	public void setInfoUser(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>eydokia.entry.info_user</code>.
	 */
	public java.lang.String getInfoUser() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>eydokia.entry.info_text</code>.
	 */
	public void setInfoText(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>eydokia.entry.info_text</code>.
	 */
	public java.lang.String getInfoText() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>eydokia.entry.info_time</code>.
	 */
	public void setInfoTime(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>eydokia.entry.info_time</code>.
	 */
	public java.sql.Timestamp getInfoTime() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>eydokia.entry.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>eydokia.entry.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Date, java.sql.Time, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Date, java.sql.Time, java.sql.Date, java.sql.Time, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ENTRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.ROOM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.SCHEDULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field7() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field8() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field9() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.INFO_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field14() {
		return org.inf.uth.eydokia.jooq.tables.Entry.ENTRY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getEntryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getRoomId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getScheduleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value7() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value8() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value9() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getInfoUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getInfoText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getInfoTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value14() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value1(java.lang.Integer value) {
		setEntryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value2(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value3(java.lang.Integer value) {
		setRoomId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value4(java.lang.Integer value) {
		setScheduleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value5(java.lang.Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value6(java.sql.Date value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value7(java.sql.Time value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value8(java.sql.Date value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value9(java.sql.Time value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value10(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value11(java.lang.String value) {
		setInfoUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value12(java.lang.String value) {
		setInfoText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value13(java.sql.Timestamp value) {
		setInfoTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord value14(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Byte value5, java.sql.Date value6, java.sql.Time value7, java.sql.Date value8, java.sql.Time value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.sql.Timestamp value13, java.sql.Timestamp value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EntryRecord
	 */
	public EntryRecord() {
		super(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY);
	}

	/**
	 * Create a detached, initialised EntryRecord
	 */
	public EntryRecord(java.lang.Integer entryId, java.lang.Integer userId, java.lang.Integer roomId, java.lang.Integer scheduleId, java.lang.Byte status, java.sql.Date startDate, java.sql.Time startTime, java.sql.Date endDate, java.sql.Time endTime, java.lang.String description, java.lang.String infoUser, java.lang.String infoText, java.sql.Timestamp infoTime, java.sql.Timestamp createTime) {
		super(org.inf.uth.eydokia.jooq.tables.Entry.ENTRY);

		setValue(0, entryId);
		setValue(1, userId);
		setValue(2, roomId);
		setValue(3, scheduleId);
		setValue(4, status);
		setValue(5, startDate);
		setValue(6, startTime);
		setValue(7, endDate);
		setValue(8, endTime);
		setValue(9, description);
		setValue(10, infoUser);
		setValue(11, infoText);
		setValue(12, infoTime);
		setValue(13, createTime);
	}
}
