/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends org.jooq.impl.UpdatableRecordImpl<org.inf.uth.eydokia.jooq.tables.records.EventsRecord> implements org.jooq.Record4<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1669146001;

	/**
	 * Setter for <code>eydokia.events.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eydokia.events.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>eydokia.events.start_date</code>.
	 */
	public void setStartDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eydokia.events.start_date</code>.
	 */
	public java.sql.Timestamp getStartDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>eydokia.events.end_date</code>.
	 */
	public void setEndDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eydokia.events.end_date</code>.
	 */
	public java.sql.Timestamp getEndDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>eydokia.events.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eydokia.events.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.inf.uth.eydokia.jooq.tables.Events.EVENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.inf.uth.eydokia.jooq.tables.Events.EVENTS.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return org.inf.uth.eydokia.jooq.tables.Events.EVENTS.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.inf.uth.eydokia.jooq.tables.Events.EVENTS.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value2(java.sql.Timestamp value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value3(java.sql.Timestamp value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord value4(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventsRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.sql.Timestamp value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventsRecord
	 */
	public EventsRecord() {
		super(org.inf.uth.eydokia.jooq.tables.Events.EVENTS);
	}

	/**
	 * Create a detached, initialised EventsRecord
	 */
	public EventsRecord(java.lang.Integer id, java.sql.Timestamp startDate, java.sql.Timestamp endDate, java.lang.String text) {
		super(org.inf.uth.eydokia.jooq.tables.Events.EVENTS);

		setValue(0, id);
		setValue(1, startDate);
		setValue(2, endDate);
		setValue(3, text);
	}
}
