/**
 * This class is generated by jOOQ
 */
package org.inf.uth.eydokia.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomRecord extends org.jooq.impl.UpdatableRecordImpl<org.inf.uth.eydokia.jooq.tables.records.RoomRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -1572072970;

	/**
	 * Setter for <code>eydokia.room.room_id</code>.
	 */
	public void setRoomId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eydokia.room.room_id</code>.
	 */
	public java.lang.Integer getRoomId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>eydokia.room.disabled</code>.
	 */
	public void setDisabled(java.lang.Boolean value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eydokia.room.disabled</code>.
	 */
	public java.lang.Boolean getDisabled() {
		return (java.lang.Boolean) getValue(1);
	}

	/**
	 * Setter for <code>eydokia.room.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eydokia.room.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>eydokia.room.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eydokia.room.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>eydokia.room.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eydokia.room.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.inf.uth.eydokia.jooq.tables.Room.ROOM.ROOM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field2() {
		return org.inf.uth.eydokia.jooq.tables.Room.ROOM.DISABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.inf.uth.eydokia.jooq.tables.Room.ROOM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.inf.uth.eydokia.jooq.tables.Room.ROOM.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return org.inf.uth.eydokia.jooq.tables.Room.ROOM.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRoomId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value2() {
		return getDisabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord value1(java.lang.Integer value) {
		setRoomId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord value2(java.lang.Boolean value) {
		setDisabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord value4(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord value5(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoomRecord values(java.lang.Integer value1, java.lang.Boolean value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoomRecord
	 */
	public RoomRecord() {
		super(org.inf.uth.eydokia.jooq.tables.Room.ROOM);
	}

	/**
	 * Create a detached, initialised RoomRecord
	 */
	public RoomRecord(java.lang.Integer roomId, java.lang.Boolean disabled, java.lang.String name, java.lang.String description, java.sql.Timestamp createTime) {
		super(org.inf.uth.eydokia.jooq.tables.Room.ROOM);

		setValue(0, roomId);
		setValue(1, disabled);
		setValue(2, name);
		setValue(3, description);
		setValue(4, createTime);
	}
}
